/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesodatos;
import java.awt.Color;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Adrian
 */
public class Ventana extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    ficheroSecuencial fs;
    FicheroAleatorio fa;
     
    public Ventana() {
        initComponents();
        dialogSecuencial.setSize(600, 400);
        dialogCrear.setSize(500,400);
        dialogAleatorio.setSize(400, 400);

    }
    public String abrirArchivo(File archivo){
      // guardamos el documento
        String documento= "";
        try{
            //try catch para evitar errores.
          entrada = new FileInputStream(archivo);
          // almacenamos el codigo ascii del documento 
          int asc;
          // pasamos el documento en ascii a un texto 
          while((asc=entrada.read())!=-1){
              // le damos a cada character su valor correspondiente 
              char c = (char)asc;
              documento+=c;
              
          }
        }catch(Exception e){
            
        }
        // ahora devuelve el texto ya escrito 
        return documento;
    }
    public String GuardarArchivo(File archivo,String Documento){
        String mensaje = null;
        try{
            salida = new FileOutputStream(archivo);
            byte[] bytxt=Documento.getBytes();
            salida.write(bytxt);
            mensaje="archivo guardado";
        }catch(Exception e){            
        }
        return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSecuencial = new javax.swing.JDialog();
        btnGuardarCambios = new javax.swing.JButton();
        btnBuscarTxt = new javax.swing.JButton();
        txtSecuencial = new java.awt.TextArea();
        txtBuscador = new java.awt.TextField();
        dialogAleatorio = new javax.swing.JDialog();
        txtFieldNombre = new javax.swing.JTextField();
        txtFieldApellidos = new javax.swing.JTextField();
        txtFieldTelefono = new javax.swing.JTextField();
        txtFieldCorreo = new javax.swing.JTextField();
        btnGuardarAleatorio = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        dialogCrear = new javax.swing.JDialog();
        btnCrearFichero = new javax.swing.JButton();
        txtCrearFichero = new java.awt.TextArea();
        dialogCopiar = new javax.swing.JDialog();
        btnSecuencial = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        elegirArchivo = new javax.swing.JButton();
        textoArea = new java.awt.TextArea();

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseClicked(evt);
            }
        });

        btnBuscarTxt.setText("Buscar Texto");
        btnBuscarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialogSecuencialLayout = new javax.swing.GroupLayout(dialogSecuencial.getContentPane());
        dialogSecuencial.getContentPane().setLayout(dialogSecuencialLayout);
        dialogSecuencialLayout.setHorizontalGroup(
            dialogSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSecuencialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogSecuencialLayout.createSequentialGroup()
                        .addComponent(txtSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogSecuencialLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarTxt)
                        .addGap(73, 116, Short.MAX_VALUE))))
            .addGroup(dialogSecuencialLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnGuardarCambios)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogSecuencialLayout.setVerticalGroup(
            dialogSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSecuencialLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGuardarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGuardarAleatorio.setText("Guardar Ingreso");

        label1.setText("Nombre");

        label2.setText("Apellidos");

        label3.setText("Telefono");

        label4.setText("Correo");

        javax.swing.GroupLayout dialogAleatorioLayout = new javax.swing.GroupLayout(dialogAleatorio.getContentPane());
        dialogAleatorio.getContentPane().setLayout(dialogAleatorioLayout);
        dialogAleatorioLayout.setHorizontalGroup(
            dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAleatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogAleatorioLayout.createSequentialGroup()
                        .addGroup(dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogAleatorioLayout.createSequentialGroup()
                        .addGroup(dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addGroup(dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(txtFieldTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnGuardarAleatorio)
                        .addContainerGap())))
        );
        dialogAleatorioLayout.setVerticalGroup(
            dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAleatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dialogAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogAleatorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogAleatorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnGuardarAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );

        dialogCrear.setBackground(new java.awt.Color(0, 0, 0));
        dialogCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCrearFichero.setText("Guardar Documento ");
        btnCrearFichero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearFicheroMouseClicked(evt);
            }
        });

        txtCrearFichero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout dialogCrearLayout = new javax.swing.GroupLayout(dialogCrear.getContentPane());
        dialogCrear.getContentPane().setLayout(dialogCrearLayout);
        dialogCrearLayout.setHorizontalGroup(
            dialogCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCrearFichero)
                .addContainerGap())
        );
        dialogCrearLayout.setVerticalGroup(
            dialogCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCrearFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
            .addGroup(dialogCrearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogCopiarLayout = new javax.swing.GroupLayout(dialogCopiar.getContentPane());
        dialogCopiar.getContentPane().setLayout(dialogCopiarLayout);
        dialogCopiarLayout.setHorizontalGroup(
            dialogCopiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogCopiarLayout.setVerticalGroup(
            dialogCopiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSecuencial.setText("Archivo Secuencial");
        btnSecuencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecuencialMouseClicked(evt);
            }
        });

        btnAleatorio.setText("Archivo Aleatorio");
        btnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAleatorioMouseClicked(evt);
            }
        });

        btnCrear.setText("Nuevo Archivo");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        btnCopiar.setText("Copiar Archivo");

        elegirArchivo.setText("Abrir Archivo");
        elegirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elegirArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(elegirArchivo)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSecuencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAleatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCopiar)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(elegirArchivo)
                .addGap(18, 18, 18)
                .addComponent(textoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elegirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirArchivoMouseClicked
        // elegimos el archivo 
        // creamos un jfilechooser para seleccionar el archivo que va a abrir el usuario.
             if(seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
           archivo=seleccionar.getSelectedFile();
           // si se puede abrir el archivo
           if(archivo.canRead()){
               // le pasa el nombre siempre y cuando sea un .txt es decir un texto plano
               if(archivo.getName().endsWith("txt")){
                   String  documento = abrirArchivo(archivo);
                   // lo imprime en la pantalla inicial
                   textoArea.setText(documento);
                   // lo imprime en la pantalla secundaria del texto secuencial              
                   txtSecuencial.setText(documento);
               }else{
                   JOptionPane.showMessageDialog(null, "No es compatible");
               }
           }
       }
    }//GEN-LAST:event_elegirArchivoMouseClicked

    private void btnSecuencialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecuencialMouseClicked
        dialogSecuencial.setAlwaysOnTop(rootPaneCheckingEnabled);
        dialogSecuencial.setVisible(true);
        // abrimos el dialog para escoger el archivo que vamos a abrir 
        if(seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
            // archivo seleccionado 
           archivo=seleccionar.getSelectedFile();
           // si se puede abrir el archivo
           if(archivo.canRead()){
               // le pasa el nombre siempre y cuando sea un .txt es decir un texto plano
               if(archivo.getName().endsWith("txt")){
                   String  documento = abrirArchivo(archivo);
                   // lo imprime en la pantalla secundaria del texto secuencial              
                   txtSecuencial.setText(documento);
               }else{
                   JOptionPane.showMessageDialog(null, "No es compatible");
               }
           }
       }
    }//GEN-LAST:event_btnSecuencialMouseClicked

    private void btnGuardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMouseClicked
         //   ficheroSecuencial.grabarDatos(archivo, datos);
         if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
             archivo=seleccionar.getSelectedFile();
             if(archivo.getName().endsWith("txt")){
                 String Documento=txtSecuencial.getText();
                 String mensaje=GuardarArchivo(archivo,Documento);
                 if(mensaje!=null){
                     JOptionPane.showMessageDialog(rootPane, mensaje);
                 }else{
                      JOptionPane.showMessageDialog(rootPane, "archivo no guardado");
                 }                
             }
         }
         
    }//GEN-LAST:event_btnGuardarCambiosMouseClicked

    private void btnBuscarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarTxtMouseClicked
        // busca la palabra que queira el usuario e indica si esta en el documento 
        String palabraBuscada ="";
        txtSecuencial.setText(null);
        txtBuscador.getText();
        txtBuscador.setText(palabraBuscada);
        
       
    }//GEN-LAST:event_btnBuscarTxtMouseClicked

    private void btnCrearFicheroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFicheroMouseClicked
        // repetimos el metodo para guardar el archivo indicado anteriormente
        // a excepcion de que aqui el texto que va a guardar lo recoge del txtCrearFichero
        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
             archivo=seleccionar.getSelectedFile();
             if(archivo.getName().endsWith("txt")){
                 String Documento=txtCrearFichero.getText();
                 String mensaje=GuardarArchivo(archivo,Documento);
                 if(mensaje!=null){
                     JOptionPane.showMessageDialog(rootPane, mensaje);
                 }else{
                      JOptionPane.showMessageDialog(rootPane, "archivo no guardado");
                 }                
             }
         }
    }//GEN-LAST:event_btnCrearFicheroMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
       dialogCrear.setAlwaysOnTop(rootPaneCheckingEnabled);
       dialogCrear.setVisible(true);
       
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAleatorioMouseClicked
        // Abrimos el archivo aleatorio
        dialogAleatorio.setAlwaysOnTop(rootPaneCheckingEnabled);
        dialogAleatorio.setVisible(true);
    }//GEN-LAST:event_btnAleatorioMouseClicked
        
       
  
    public static void main(String args[]) throws FileNotFoundException {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnBuscarTxt;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearFichero;
    private javax.swing.JButton btnGuardarAleatorio;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnSecuencial;
    private javax.swing.JDialog dialogAleatorio;
    private javax.swing.JDialog dialogCopiar;
    private javax.swing.JDialog dialogCrear;
    private javax.swing.JDialog dialogSecuencial;
    private javax.swing.JButton elegirArchivo;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextArea textoArea;
    private java.awt.TextField txtBuscador;
    private java.awt.TextArea txtCrearFichero;
    private javax.swing.JTextField txtFieldApellidos;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldNombre;
    private javax.swing.JTextField txtFieldTelefono;
    private java.awt.TextArea txtSecuencial;
    // End of variables declaration//GEN-END:variables
}
